[2024-12-13T00:24:04.696+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-13T00:24:04.715+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecobalyse_dag.Load_Data manual__2024-12-13T00:21:51.525975+00:00 [queued]>
[2024-12-13T00:24:04.724+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecobalyse_dag.Load_Data manual__2024-12-13T00:21:51.525975+00:00 [queued]>
[2024-12-13T00:24:04.724+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2024-12-13T00:24:04.737+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Load_Data> on 2024-12-13 00:21:51.525975+00:00
[2024-12-13T00:24:04.743+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1091) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-13T00:24:04.744+0000] {standard_task_runner.py:72} INFO - Started process 1093 to run task
[2024-12-13T00:24:04.746+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecobalyse_dag', 'Load_Data', 'manual__2024-12-13T00:21:51.525975+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/data_transformations.py', '--cfg-path', '/tmp/tmplsl2mip2']
[2024-12-13T00:24:04.747+0000] {standard_task_runner.py:105} INFO - Job 223: Subtask Load_Data
[2024-12-13T00:24:04.793+0000] {task_command.py:467} INFO - Running <TaskInstance: ecobalyse_dag.Load_Data manual__2024-12-13T00:21:51.525975+00:00 [running]> on host c8c82134bf48
[2024-12-13T00:24:05.031+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecobalyse_dag' AIRFLOW_CTX_TASK_ID='Load_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T00:21:51.525975+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T00:21:51.525975+00:00'
[2024-12-13T00:24:05.032+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-13T00:24:05.032+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-13T00:24:05.032+0000] {logging_mixin.py:190} INFO - Current task name:Load_Data state:running start_date:2024-12-13 00:24:04.715511+00:00
[2024-12-13T00:24:05.032+0000] {logging_mixin.py:190} INFO - Dag name:ecobalyse_dag and current dag run status:running
[2024-12-13T00:24:05.033+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-13T00:24:05.062+0000] {base.py:84} INFO - Retrieving connection 'ecobalyse_database_connection'
[2024-12-13T00:24:05.094+0000] {logging_mixin.py:190} INFO - 0       (0.14571477426236856, 24.225601759405862, 111....
1       (0.021157835040455618, 2.7420274483981206, 7.8...
2       (0.18125129163341008, 20.854181978411905, 91.0...
3       (0.3056645105082514, 32.17516972790083, 109.14...
4       (0.094096956587051, 12.514815452447031, 56.131...
                              ...                        
1995    (0.01362238213189429, 1.2771671079348925, 8.48...
1996    (0.012454408473352836, 2.1197237799929205, 8.5...
1997    (0.03795029342355499, 6.383826107632738, 20.20...
1998    (0.1529159690753016, 20.192346578481374, 100.6...
1999    (0.19164122186098212, 19.621334025332043, 76.9...
Length: 2000, dtype: object
[2024-12-13T00:24:05.095+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_transformations.py", line 158, in insert_data_into_postgres
    cursor.execute(insert_query,record)
psycopg2.errors.UndefinedColumn: column "surfaceMass" of relation "ecobalyse_table" does not exist
LINE 38:                                 "surfaceMass" , 
                                         ^

[2024-12-13T00:24:05.105+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-13T00:24:05.106+0000] {logging_mixin.py:190} INFO - Task start:2024-12-13 00:24:04.715511+00:00 end:2024-12-13 00:24:05.105132+00:00 duration:0.389621
[2024-12-13T00:24:05.106+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): Load_Data> dag:<DAG: ecobalyse_dag> dagrun:<DagRun ecobalyse_dag @ 2024-12-13 00:21:51.525975+00:00: manual__2024-12-13T00:21:51.525975+00:00, state:running, queued_at: 2024-12-13 00:21:51.532783+00:00. externally triggered: True>
[2024-12-13T00:24:05.106+0000] {logging_mixin.py:190} INFO - Failure caused by column "surfaceMass" of relation "ecobalyse_table" does not exist
LINE 38:                                 "surfaceMass" , 
                                         ^
[2024-12-13T00:24:05.106+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ecobalyse_dag, task_id=Load_Data, run_id=manual__2024-12-13T00:21:51.525975+00:00, execution_date=20241213T002151, start_date=20241213T002404, end_date=20241213T002405
[2024-12-13T00:24:05.119+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-13T00:24:05.120+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 223 for task Load_Data (column "surfaceMass" of relation "ecobalyse_table" does not exist
LINE 38:                                 "surfaceMass" , 
                                         ^
; 1093)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_transformations.py", line 158, in insert_data_into_postgres
    cursor.execute(insert_query,record)
psycopg2.errors.UndefinedColumn: column "surfaceMass" of relation "ecobalyse_table" does not exist
LINE 38:                                 "surfaceMass" , 
                                         ^

[2024-12-13T00:24:05.159+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-13T00:24:05.178+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-13T00:24:05.180+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
