[2024-12-12T20:47:55.037+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-12T20:47:55.165+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecobalyse_dag.transform_json_file_to_dataframe manual__2024-12-12T20:45:48.618372+00:00 [queued]>
[2024-12-12T20:47:55.174+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecobalyse_dag.transform_json_file_to_dataframe manual__2024-12-12T20:45:48.618372+00:00 [queued]>
[2024-12-12T20:47:55.174+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2024-12-12T20:47:55.183+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_json_file_to_dataframe> on 2024-12-12 20:45:48.618372+00:00
[2024-12-12T20:47:55.188+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=826) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-12T20:47:55.189+0000] {standard_task_runner.py:72} INFO - Started process 828 to run task
[2024-12-12T20:47:55.190+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecobalyse_dag', 'transform_json_file_to_dataframe', 'manual__2024-12-12T20:45:48.618372+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/data_transformations.py', '--cfg-path', '/tmp/tmpaplcylrg']
[2024-12-12T20:47:55.191+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask transform_json_file_to_dataframe
[2024-12-12T20:47:55.240+0000] {task_command.py:467} INFO - Running <TaskInstance: ecobalyse_dag.transform_json_file_to_dataframe manual__2024-12-12T20:45:48.618372+00:00 [running]> on host c67d6daee869
[2024-12-12T20:47:55.304+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecobalyse_dag' AIRFLOW_CTX_TASK_ID='transform_json_file_to_dataframe' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T20:45:48.618372+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T20:45:48.618372+00:00'
[2024-12-12T20:47:55.305+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-12T20:47:55.305+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-12T20:47:55.305+0000] {logging_mixin.py:190} INFO - Current task name:transform_json_file_to_dataframe state:running start_date:2024-12-12 20:47:55.165951+00:00
[2024-12-12T20:47:55.306+0000] {logging_mixin.py:190} INFO - Dag name:ecobalyse_dag and current dag run status:running
[2024-12-12T20:47:55.306+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-12T20:47:55.306+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    self.op_kwargs = self.determine_kwargs(context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 247, in determine_kwargs
    return KeywordParameters.determine(self.python_callable, self.op_args, context).unpacking()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 168, in determine
    raise ValueError(f"The key {name!r} in args is a part of kwargs and therefore reserved.")
ValueError: The key 'task_instance' in args is a part of kwargs and therefore reserved.
[2024-12-12T20:47:55.320+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-12T20:47:55.321+0000] {logging_mixin.py:190} INFO - Task start:2024-12-12 20:47:55.165951+00:00 end:2024-12-12 20:47:55.319787+00:00 duration:0.153836
[2024-12-12T20:47:55.321+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_json_file_to_dataframe> dag:<DAG: ecobalyse_dag> dagrun:<DagRun ecobalyse_dag @ 2024-12-12 20:45:48.618372+00:00: manual__2024-12-12T20:45:48.618372+00:00, state:running, queued_at: 2024-12-12 20:45:48.622303+00:00. externally triggered: True>
[2024-12-12T20:47:55.322+0000] {logging_mixin.py:190} INFO - Failure caused by The key 'task_instance' in args is a part of kwargs and therefore reserved.
[2024-12-12T20:47:55.322+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ecobalyse_dag, task_id=transform_json_file_to_dataframe, run_id=manual__2024-12-12T20:45:48.618372+00:00, execution_date=20241212T204548, start_date=20241212T204755, end_date=20241212T204755
[2024-12-12T20:47:55.336+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-12T20:47:55.337+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task transform_json_file_to_dataframe (The key 'task_instance' in args is a part of kwargs and therefore reserved.; 828)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    self.op_kwargs = self.determine_kwargs(context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 247, in determine_kwargs
    return KeywordParameters.determine(self.python_callable, self.op_args, context).unpacking()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 168, in determine
    raise ValueError(f"The key {name!r} in args is a part of kwargs and therefore reserved.")
ValueError: The key 'task_instance' in args is a part of kwargs and therefore reserved.
[2024-12-12T20:47:55.363+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-12T20:47:55.379+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-12T20:47:55.381+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
